<?php
/**
 * @author Archigos
 * @copyright 2012
 * Originally based on the "Addon" to Maraschino by 'hernandito' of XBMC Forums.
 * Please do not edit this file, check the Readme.md and edit 'settings.ini' instead
 */

require 'includes/required/errorreporting.php';
require 'includes/required/defaults.php';
require 'includes/required/header.php';


 
?>
<meta name = "viewport" content = "initial-scale = 1.0, user-scalable = no">

<style type="text/css">

body {
	background-color: #737373;
	background-attachment: scroll;
	background-repeat: repeat;
	background-position: left top;

	margin-top: 0px;
	margin-right: 5px;
	margin-bottom: 0px;
	margin-left: 5px;
	padding-top: 5px;
	padding-right: 5px;
	padding-bottom: 0px;
	padding-left: 5px;
	background-image: url(includes/images/grey_wash_wall.png);
}

.technology{
	cursor: hand;
	cursor: pointer;
	font-family: arial, helvetica, sans-serif;
	font-size: 16px;
	font-weight: bold;
	color: #2F7BB9;
	padding: 2px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	margin-left: 0px;
	border-bottom-width: 1px;
	border-bottom-style: solid;
	border-bottom-color: #CCCCCC;
}

.technology:hover{
	color: #B70000;
}

#rss {
	font-size: 16px;
	font-family: Verdana, Geneva, sans-serif;
	color: #036;
	padding: 12px;
	margin: 3px 3px 3px -1px;
	-webkit-border-radius: 10px;
	border-radius: 3px;
	height: auto;
	border: 1px none #4D4D4D;
	margin-top: 0px;
	left: 4px;
	background-color: #EFEFEF;
	-webkit-box-shadow: 2px 2px 8px 3px rgba(0, 0, 0, .3);
	box-shadow: 2px 2px 8px 3px rgba(0, 0, 0, .3);
	font-weight: bold;
}
#rss a {
	text-decoration: none;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	color: #525252;
	font-weight: normal;
}
#rss a:visited {
	color: #B2B2B2;
	font-weight: normal;
}

#rss img {
	margin-bottom: 0px;
	padding-bottom: 0px;	
}

#rss a:hover {
	color: #BF0005;
	
}

#rss  li {
	border-bottom-width: thin;
	border-bottom-style: solid;
	border-bottom-color: #B5D8E6;
	list-style-type: none;
	line-height: 10pt;
	padding-top: 3px;
	padding-bottom: 3px;
}

#rss strong {
	text-decoration: none;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color: #039;
	padding-left: 0px;
}
#mainrss {
	height: 100%;
	position: relative;
	vertical-align: top;
	padding-top: 0px;
	padding-right: 0px;
	padding-bottom: 00px;
	padding-left: 0px;
}



/* RSS Feeds */
.rss-box {
	width: 100%;
}
.rss-title, rss-title a {
    margin: 0px 0;
    padding: 0;
}
.rss-items {
    margin: 3px;
    padding: 0px;	

}

#topbar{
	background-color: #000;
	-webkit-border-radius: 3px;
	border-radius: 6px;
	font-size: 12px;
	font-weight: normal;
	text-decoration: none;
	padding-top: 7px;
	padding-right: 0px;
	padding-bottom: 5px;
	padding-left: 5px;
	margin-bottom: 5px;
}

#topbar strong{
	font-family: Verdana, Geneva, sans-serif;
	font-size: 11px;
	font-style: normal;
	font-weight: normal;
	color: #FC0;
	text-decoration: none;	
	margin-left: 15px;
		
		}
#topbar img{
	position: relative;
	top: 7px;
	left: 6px;
}
</style> 



<body topmargin="0" >


<div id="mainrss">   

<table width="100%" border="0" cellspacing="3" cellpadding="0" >

 
  <tr valign="top">
	<td width="98%" >
        <div style="background-color: #E8F7FF" id="rss" class="rss">
			<img src="includes/images/logo_smalrlslog.png" width="96" height="25">
			<?php writeRSSName($ini['feed3name']); ?>
            <?php writeRSS($ini['feed3'],$rsscount); ?>
   		</div>
	</td>
        
  </tr>
  

  <tr valign="top">      
	<td >
		<div style="background-color: #E8F7FF" id="rss" class="rss">
			<img src="includes/images/logo_smallscnsrc.png" width="172" height="25">
			<?php writeRSSName($ini['feed4name']); ?>
			<?php writeRSS($ini['feed4'],$rsscount); ?>
		</div>   
    </td>
  </tr>  


  
</table>

</div>

</body>
</html>